/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName?: string;
  slogan?: string;
  phone?: string;
  email?: string;
  serviceArea?: string;
  heroHeadline?: string;
  heroHeadlineAccent?: string;
  heroDescription?: string;
  heroPrimaryCta?: string;
  heroSecondaryCta?: string;
  navigation?: Array<{
    label?: string;
    page?: PageReference;
    url?: string;
    _key: string;
  }>;
  footerLinks?: Array<{
    label?: string;
    page?: PageReference;
    url?: string;
    _key: string;
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  template?:
    | "standard"
    | "home"
    | "contact"
    | "productsIndex"
    | "productCategory"
    | "productDetail"
    | "moodboard";
  intro?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  labels?: {
    sectionTitle?: string;
    backLabel?: string;
    reservationTitle?: string;
    phoneLabel?: string;
    emailLabel?: string;
    serviceAreaLabel?: string;
    emptyState?: string;
    breadcrumbCatalogLabel?: string;
    specDimensionsLabel?: string;
    productCodeLabel?: string;
    specCapacityLabel?: string;
    capacityUnit?: string;
    priceWeekendSuffix?: string;
    priceWeekSuffix?: string;
    quoteCtaLabel?: string;
    backToCategoryPrefix?: string;
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  code?: string;
  slug?: Slug;
  category?: CategoryReference;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  dimensions?: string;
  capacity?: number;
  priceWeek?: number;
  priceWeekend?: number;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: string;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PageReference
  | SiteSettings
  | Page
  | Slug
  | CategoryReference
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity.queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  companyName, slogan, phone, email, serviceArea,  heroHeadline, heroHeadlineAccent, heroDescription, heroPrimaryCta, heroSecondaryCta,  navigation[]{ _key, label, url, page->{ title, "slug": slug.current } },  footerLinks[]{ _key, label, url, page->{ title, "slug": slug.current } }}
export type SITE_SETTINGS_QUERY_RESULT = {
  companyName: string | null;
  slogan: string | null;
  phone: string | null;
  email: string | null;
  serviceArea: string | null;
  heroHeadline: string | null;
  heroHeadlineAccent: string | null;
  heroDescription: string | null;
  heroPrimaryCta: string | null;
  heroSecondaryCta: string | null;
  navigation: Array<{
    _key: string;
    label: string | null;
    url: string | null;
    page: {
      title: string | null;
      slug: string | null;
    } | null;
  }> | null;
  footerLinks: Array<{
    _key: string;
    label: string | null;
    url: string | null;
    page: {
      title: string | null;
      slug: string | null;
    } | null;
  }> | null;
} | null;

// Source: src/lib/sanity.queries.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == "category"] | order(order asc){  _id, name, "slug": slug.current, description, order, image{ asset, alt, hotspot, crop }}
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  order: number | null;
  image: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: src/lib/sanity.queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{  _id, name, "slug": slug.current, description}
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
} | null;

// Source: src/lib/sanity.queries.ts
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[_type == "product" && category._ref == $categoryId] | order(order asc){  _id, name, code, "slug": slug.current, dimensions, capacity,  priceWeek, priceWeekend, images[0]{ asset, alt }, description}
export type PRODUCTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  code: string | null;
  slug: string | null;
  dimensions: string | null;
  capacity: number | null;
  priceWeek: number | null;
  priceWeekend: number | null;
  images: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;

// Source: src/lib/sanity.queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{  _id, name, code, "slug": slug.current,  category->{ _id, name, "slug": slug.current },  images[]{ asset, alt, hotspot, crop, _key },  description, dimensions, capacity, priceWeek, priceWeekend}
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  code: string | null;
  slug: string | null;
  category: {
    _id: string;
    name: string | null;
    slug: string | null;
  } | null;
  images: Array<{
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    _key: string;
  }> | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  dimensions: string | null;
  capacity: number | null;
  priceWeek: number | null;
  priceWeekend: number | null;
} | null;

// Source: src/lib/sanity.queries.ts
// Variable: ALL_PRODUCT_SLUGS_QUERY
// Query: *[_type == "product"]{  "slug": slug.current, "categorie": category->slug.current}
export type ALL_PRODUCT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
  categorie: string | null;
}>;

// Source: src/lib/sanity.queries.ts
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  title,  "slug": slug.current,  template,  intro,  labels{    sectionTitle,    backLabel,    reservationTitle,    phoneLabel,    emailLabel,    serviceAreaLabel,    emptyState,    breadcrumbCatalogLabel,    specDimensionsLabel,    productCodeLabel,    specCapacityLabel,    capacityUnit,    priceWeekendSuffix,    priceWeekSuffix,    quoteCtaLabel,    backToCategoryPrefix  },  content}
export type PAGE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  template:
    | "contact"
    | "home"
    | "moodboard"
    | "productCategory"
    | "productDetail"
    | "productsIndex"
    | "standard"
    | null;
  intro: string | null;
  labels: {
    sectionTitle: string | null;
    backLabel: string | null;
    reservationTitle: string | null;
    phoneLabel: string | null;
    emailLabel: string | null;
    serviceAreaLabel: string | null;
    emptyState: string | null;
    breadcrumbCatalogLabel: string | null;
    specDimensionsLabel: string | null;
    productCodeLabel: string | null;
    specCapacityLabel: string | null;
    capacityUnit: string | null;
    priceWeekendSuffix: string | null;
    priceWeekSuffix: string | null;
    quoteCtaLabel: string | null;
    backToCategoryPrefix: string | null;
  } | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  companyName, slogan, phone, email, serviceArea,\n  heroHeadline, heroHeadlineAccent, heroDescription, heroPrimaryCta, heroSecondaryCta,\n  navigation[]{ _key, label, url, page->{ title, "slug": slug.current } },\n  footerLinks[]{ _key, label, url, page->{ title, "slug": slug.current } }\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "category"] | order(order asc){\n  _id, name, "slug": slug.current, description, order, image{ asset, alt, hotspot, crop }\n}': ALL_CATEGORIES_QUERY_RESULT;
    '*[_type == "category" && slug.current == $slug][0]{\n  _id, name, "slug": slug.current, description\n}': CATEGORY_BY_SLUG_QUERY_RESULT;
    '*[_type == "product" && category._ref == $categoryId] | order(order asc){\n  _id, name, code, "slug": slug.current, dimensions, capacity,\n  priceWeek, priceWeekend, images[0]{ asset, alt }, description\n}': PRODUCTS_BY_CATEGORY_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug][0]{\n  _id, name, code, "slug": slug.current,\n  category->{ _id, name, "slug": slug.current },\n  images[]{ asset, alt, hotspot, crop, _key },\n  description, dimensions, capacity, priceWeek, priceWeekend\n}': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[_type == "product"]{\n  "slug": slug.current, "categorie": category->slug.current\n}': ALL_PRODUCT_SLUGS_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n  _id,\n  title,\n  "slug": slug.current,\n  template,\n  intro,\n  labels{\n    sectionTitle,\n    backLabel,\n    reservationTitle,\n    phoneLabel,\n    emailLabel,\n    serviceAreaLabel,\n    emptyState,\n    breadcrumbCatalogLabel,\n    specDimensionsLabel,\n    productCodeLabel,\n    specCapacityLabel,\n    capacityUnit,\n    priceWeekendSuffix,\n    priceWeekSuffix,\n    quoteCtaLabel,\n    backToCategoryPrefix\n  },\n  content\n}': PAGE_BY_SLUG_QUERY_RESULT;
  }
}
